# Generated by Django 2.2.5 on 2019-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=177)),
                ('year', models.CharField(max_length=4)),
                ('rated', models.CharField(max_length=5, null=True)),
                ('released', models.DateField()),
                ('runtime', models.IntegerField()),
                ('genre', models.CharField(max_length=70, null=True)),
                ('director', models.CharField(max_length=70)),
                ('writer', models.CharField(max_length=255)),
                ('actors', models.CharField(max_length=255)),
                ('plot', models.TextField(null=True)),
                ('language', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=47)),
                ('awards', models.CharField(max_length=255, null=True)),
                ('poster', models.URLField(null=True)),
                ('metascore', models.IntegerField(null=True)),
                ('imdbrating', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('imdbvotes', models.IntegerField(null=True)),
                ('imdbid', models.CharField(max_length=40, null=True, unique=True)),
                ('type', models.CharField(max_length=20, null=True)),
                ('dvd', models.DateField(null=True)),
                ('boxoffice', models.IntegerField(null=True)),
                ('production', models.CharField(max_length=40, null=True)),
                ('website', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=20)),
                ('movie', models.ForeignKey(on_delete='cascade', related_name='ratings', to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('movie', models.ForeignKey(on_delete='cascade', related_name='comments', to='movies.Movie')),
            ],
        ),
    ]
